### ISSUE TITLE
Crash during snap synching

### ISSUE THREAD

**Issue by egonspace** [wemixarchive/go-wbft#48]
#### System information

A node has been crashed during snap synching with mainnet.

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour
```
INFO [12-05|14:05:06.129] Syncing: chain download in progress      synced=0.77%  chain=1.12GiB   headers=540,672@1.10GiB    bodies=516,096@6.82MiB receipts=516,096@6.12MiB eta=32h9m46.015s
INFO [12-05|14:05:06.129] Syncing: state download in progress      synced=32.28% state=5.59GiB    accounts=2,720,474@97.55MiB slots=24,918,785@5.49GiB  codes=1259@12.11MiB eta=31m15.875s
INFO [12-05|14:05:14.257] Syncing: state download in progress      synced=34.14% state=5.64GiB    accounts=2,872,417@103.25MiB slots=25,118,887@5.53GiB  codes=1311@12.50MiB eta=28m56.673s
INFO [12-05|14:05:15.643] Syncing: chain download in progress      synced=0.80%  chain=1.16GiB   headers=542,720@1.15GiB    bodies=536,710@7.08MiB receipts=536,710@6.38MiB eta=31h14m45.067s
WARN [12-05|14:05:20.985] Storage slots failed proof               peer=7b3dbc9e reqid=5,464,152,439,022,437,019 err="invalid proof, want hash 46dc5e738140a36d4504dfec76ce70352afa42e61b4ac0fe15fa443e744b5bd8, got 121c60f2907f7f4678c2dd9d2bd3beaf6e3d68defe26d3af019e67192c181bcf"
INFO [12-05|14:05:20.985] Looking for peers                        peercount=0 tried=0 static=1
INFO [12-05|14:05:20.986] Syncing: state download in progress      synced=36.97% state=5.68GiB    accounts=2,908,353@111.82MiB slots=25,269,275@5.55GiB  codes=1386@13.33MiB eta=25m44.187s
INFO [12-05|14:05:22.094] Block synchronisation finished
WARN [12-05|14:05:22.094] Synchronisation failed, retrying         err="no peers to keep download active"
panic: close of closed channel

goroutine 4199 [running]:
github.com/ethereum/go-ethereum/consensus/wemix.(*WemixConsensus).Stop(...)
        github.com/ethereum/go-ethereum/consensus/wemix/consensus.go:83
github.com/ethereum/go-ethereum/miner.(*worker).stop(0xc0001a0fc8)
        github.com/ethereum/go-ethereum/miner/worker.go:402 +0x4e
github.com/ethereum/go-ethereum/miner.(*Miner).update(0xc0006443c0)
        github.com/ethereum/go-ethereum/miner/miner.go:130 +0x389
created by github.com/ethereum/go-ethereum/miner.New in goroutine 1
        github.com/ethereum/go-ethereum/miner/miner.go:98 +0x1e5

```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by egonspace** [comment]
There are two problem on this.
- failed in validation of state synching: `invalid proof, want hash 46dc5e...`
- panic on closing engine

second problem is handled by https://github.com/wemixarchive/go-wemix-qbft/pull/49
